services:
  # Databases
  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-playlist:
    image: postgres:15
    environment:
      POSTGRES_DB: playlist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./playlist-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-playlist-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d playlist_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-user:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./user-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-user-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-video:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_video_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-monitoring:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongodb_monitoring_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb-social:
    image: mongo:6
    ports:
      - "27019:27017"
    volumes:
      - mongodb_social_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Services
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=:50051"]
      interval: 10s
      start_period: 30s
      timeout: 5s
      retries: 5
    depends_on:
      mysql-user:
        condition: service_healthy
    env_file:
      - ./user-service/.env

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      postgres-auth:
        condition: service_healthy
      user-service:
        condition: service_healthy
    env_file:
      - ./auth-service/.env

  playlist-service:
    build:
      context: .
      dockerfile: ./playlist-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      postgres-playlist:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./playlist-service/.env

  video-service:
    build:
      context: .
      dockerfile: ./video-service/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      mongodb-video:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./video-service/.env

  social-service:
    build:
      context: .
      dockerfile: ./social-service/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      mongodb-social:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./social-service/.env

  billing-service:
    build:
      context: .
      dockerfile: ./billing-service/Dockerfile
    ports:
      - "3005:3005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./billing-service/.env

  monitoring-service:
    build:
      context: .
      dockerfile: ./monitoring-service/Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      mongodb-monitoring:
        condition: service_healthy
    env_file:
      - ./monitoring-service/.env

  email-service:
    build:
      context: .
      dockerfile: ./email-service/Dockerfile
    ports:
      - "3007:3007"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./email-service/.env

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      user-service:
        condition: service_healthy
      # Temporarily disabling other dependencies to debug startup
      # auth-service:
      #   condition: service_healthy
      # playlist-service:
      #   condition: service_healthy
      # video-service:
      #   condition: service_healthy
      # social-service:
      #   condition: service_healthy
      # billing-service:
      #   condition: service_healthy
      # monitoring-service:
      #   condition: service_healthy
      # email-service:
      #   condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./api-gateway/.env

volumes:
  postgres-auth-data:
  postgres-playlist-data:
  mysql-user-data:
  mongodb_video_data:
  mongodb_monitoring_data:
  mongodb_social_data:
